#Hugo configuration
title = "Testyin"
baseURL = "https:\/\/testyin.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
firstpartycookies = true
cookiedomain = "testyin.com"
